/*
Warm up

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

  var a=[];
   a[0]=1;
   a[1]=1;
   var sum=0;
   var k;
   for( var i=1;i<=30000;i++){
   	a[i+1]=a[i-1]+a[i];
   	//console.log(a[i]);
   }
   var j=1;
	while(a[j]<=4000000){
     	if(a[j]%2===0){
		 	sum = sum+a[j];
		 	
	  	 }
	  	 j++;
  	}

console.log(sum);
